filebeat.inputs:
  - type: log
    paths:
      - /var/log/micro.service.email.log
output.logstash:
  hosts: ["logstash:5044"]
  index: "filebeat"
output.console:
  pretty: true
filebeat.modules:
  - module: logstash